name: Build & Deploy to HostGator

on:
  push:
    branches: [ main, master ]   # roda quando fizer push em main ou master
  workflow_dispatch:             # permite rodar manualmente pelo Actions

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Prep npm (estabilidade)
        run: |
          npm config set audit false
          npm config set fund false
          npm config set fetch-retries 5
          npm config set fetch-retry-factor 2
          npm config set fetch-retry-maxtimeout 60000

      - name: Install dependencies
        working-directory: frontend
        run: npm install --legacy-peer-deps --no-audit --no-fund

      # Garante peer deps exigidas por webpack/schema-utils
      - name: Ensure webpack peer deps (ajv & ajv-keywords)
        working-directory: frontend
        run: npm install --no-save ajv@^8 ajv-keywords@^5 --legacy-peer-deps

      - name: Build React app
        working-directory: frontend
        run: npm run build

      - name: Deploy via FTP to HostGator
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: frontend/build/
          server-dir: ./              # publica na raiz do login FTP (já é /public_html)
          exclude: |
            **/.git*
            **/.github/**
            **/.htaccess
          dangerous-clean-slate: false
